{% set name = "everett" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/willkg/everett/archive/v{{ version }}.tar.gz
  sha256: 1b1c2a3998e7de8fb46ccb17d6a206e70f5263745358d719135af4b37d667a89

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - everett
    - everett.ext
    - everett.manager
    - everett.component

about:
  home: https://github.com/willkg/everett
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: Configuration library for Python applications
  doc_url: https://pypi.org/project/everett/
  dev_url: ttps://github.com/willkg/everett

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - benhuff
    - rluria14
