travis:
  secure:
    BINSTAR_TOKEN: DFVZyzLPngg+yI2uicR7EPcMfl3yPjQuEOIkmZlUFzYy9N1zuq2LYJgdoFm8ilDPXprm/Kc9MVA8faCSJ7vUCjfzi/NF0uLcHPYMMnXtEXgx/1O5sou1ZoT+QG0XcFPpaUjLaEbVId6UUE9KwUhHtCCFJClQP/L+7rZKAypiPPk6GHlYSALkgiYK9fRQ0+tsWCq2VNncTRL8V9ScImJpt/zzwUOtPazqDWINPYOplCdKO9LQ45uHxXHQFbsU5M6v8LnnRmiNYICGH62hECVU4sbYhJdwTm5K4w8qf0ioCb3/9vOz0fiqlqELbmlLY+6EoZJ/PE2xsNLcu+n5Vh9r6PPxZBpXhKyi50nj+mHvxLXyS3fMrcekFxmMIdMNy9h9zs7050j396hFZLSVapsT2VcmqEMn8/U9Q82cizUeh60NyPpVInv5PUJWQnAOA0lkEPhFfeCK/CON6izyDyPH63y98tAF4EcrWToVxCucHifwwljktOt+6oVgN05sCXRtT80pFB8QcZUYB6caw1gcQhxE7rsOeq89u9w4w3iN+j2km/l1TlQjNJAM37z9ncw2Rpxe76X9DTdQ5prLBXP9fNWr6B5tSApOgqRZXb4tX1BHFr5r71maSJg8JfvcEpl0SOjFrgLmXZcynUjTKofqnsiZACbZdxK2QsN7DiZrehw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
